name: default

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
  pull_request:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Run tests
        run: ./gradlew test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: last-test-artifact
          path: build
          retention-days: 1

  sonar:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: last-test-artifact

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Send report to sonar
        run: ./gradlew sonarqube -Dsonar.login=$SONAR_LOGIN -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.branch.name=$GITHUB_REF
        env:
          SONAR_ORGANIZATION: ${{secrets.SONAR_ORGANIZATION}}
          SONAR_LOGIN: ${{secrets.SONAR_LOGIN}}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Send report to sonar
        run: ./gradlew build -x test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: last-build-artifact
          path: build
          retention-days: 1

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: last-build-artifact

      - name: Build Docker Image
        run: docker build -t mebr0/integrated-twitter .
