name: default

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
  pull_request:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - run: git fetch

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew build sonarqube --info
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          # SONAR_ORGANIZATION: ${{secrets.SONAR_ORGANIZATION}}
          # SONAR_LOGIN: ${{secrets.SONAR_LOGIN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - run: cat build/customJacocoReportDir/test/jacocoTestReport.xml

      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: last-test-artifact
          path: |
            build
          retention-days: 1

#  sonar:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Download Artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: last-test-artifact
#          path: build
#
#      - name: Install JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#
#      - name: Validate Gradle wrapper
#        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#
#      - name: Cache SonarQube packages
#        uses: actions/cache@v1
#        with:
#          path: ~/.sonar/cache
#          key: ${{ runner.os }}-sonar
#          restore-keys: ${{ runner.os }}-sonar
#
#      - name: Cache Gradle packages
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - run: cat build/customJacocoReportDir/test/jacocoTestReport.xml
#
#      - name: Send report to sonar
#        run: ./gradlew sonarqube -Dsonar.login=$SONAR_LOGIN -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.branch.name=${GITHUB_REF#refs/heads/}
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#          SONAR_ORGANIZATION: ${{secrets.SONAR_ORGANIZATION}}
#          SONAR_LOGIN: ${{secrets.SONAR_LOGIN}}
#
#      - name: Cleanup Gradle Cache
#        run: |
#          rm -f ~/.gradle/caches/modules-2/modules-2.lock
#          rm -f ~/.gradle/caches/modules-2/gc.properties

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Send report to sonar
        run: ./gradlew build -x test

      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: last-build-artifact
          path: |
            build
          retention-days: 1

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: last-build-artifact
          path: build

      - name: Build Docker Image
        run: docker build -t mebr0/integrated-twitter .
